FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY frontend/node-app/package*.json ./
RUN npm ci
COPY frontend/node-app/ ./
RUN npm run build

FROM nginx:1.30.4-alpine
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend-builder /app/dist/node-app/browser /usr/share/nginx/html
EXPOSE 8080
# docker build -f nginx/dockerfile -t nginximg .
# docker run --name nginxcont --net mynet -p 8080:8080 nginximg