FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD [ "node", "dist/main.js"]


#-- to run individual container. now being done through compose file. 
#build cmd-  docker build -t nestapi .
#network- docker network create mynet
#run cmd- docker run -d --name nestapi --net mynet --env-file .env -p 3000:3000 nestapi   